# Usa la imagen oficial de MongoDB
FROM mongo:8.0

# Crea un directorio de datos dentro del contenedor
RUN mkdir -p /data/db

# Expone el puerto por defecto de MongoDB
EXPOSE 27017

# Comando por defecto para iniciar MongoDB
CMD ["mongod"]
#Comando 