version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_inventarios
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: inventarios

  postgres:
    image: postgres:15
    container_name: postgres_ventas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: ventas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sigas_network

volumes:
  postgres_data:
    driver: local

networks:
  sigas_network:
    driver: bridge
