version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_inventarios
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: inventarios
