FROM mysql:8.0

# Establece las variables de entorno para MySQL
ENV MYSQL_DATABASE=empleados
ENV MYSQL_ROOT_PASSWORD=your_root_password
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin_password

EXPOSE 3306
