# Usar la imagen oficial de PostgreSQL
FROM postgres:latest

# Establecer las variables de entorno necesarias para inicializar la base de datos
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=rootpassword
ENV POSTGRES_DB=ventas

# Exponer el puerto 5432 de PostgreSQL
EXPOSE 5432

# No es necesario especificar un CMD, ya que la imagen oficial ya está configurada para arrancar PostgreSQL por defecto
